#!/bin/sh

# Identifier, do not change if modifying:
#DarkyenusTimeTrackerHookScript_00001

# Script (can be modified, but may be overwritten if new plugin version is installed):

DTT_TIME="$(dirname "$0")/../.darkyenus_time_tracker"

if [ -e "$DTT_TIME" ]
then
	TIME_TOTAL_SEC=$(cat $DTT_TIME)
	TIME_REMAINING_SEC="$TIME_TOTAL_SEC"
	TIME_MESSAGE=""
	if [ $TIME_REMAINING_SEC -ge 3600 ]
	then
		TIME_MESSAGE="$TIME_MESSAGE $(($TIME_REMAINING_SEC / 3600)) hour"
		if [ $TIME_REMAINING_SEC -lt 3600 -o $TIME_REMAINING_SEC -ge 7200 ]
		then
		    TIME_MESSAGE="${TIME_MESSAGE}s"
		fi
		TIME_REMAINING_SEC=$(($TIME_REMAINING_SEC % 3600))
	fi

	if [ $TIME_REMAINING_SEC -ge 60 ]
	then
		TIME_MESSAGE="$TIME_MESSAGE $(($TIME_REMAINING_SEC / 60)) minute"
		if [ $TIME_REMAINING_SEC -lt 60 -o $TIME_REMAINING_SEC -ge 120 ]
		then
			TIME_MESSAGE="${TIME_MESSAGE}s"
		fi
        	TIME_REMAINING_SEC=$(($TIME_REMAINING_SEC % 60))
	fi

	if [ $TIME_REMAINING_SEC -gt 0 ]
	then
		TIME_MESSAGE="$TIME_MESSAGE $TIME_REMAINING_SEC second"
		if [ $TIME_REMAINING_SEC -ne 1 ]
		then
			TIME_MESSAGE="${TIME_MESSAGE}s"
		fi
	fi

        if [ $TIME_TOTAL_SEC -gt 0 ]
	then

		printf "\n\nTook$TIME_MESSAGE" >> $1
		echo "0" > $DTT_TIME
		echo "Commit took$TIME_MESSAGE"
	else
		echo "Commit took no time, not recording"
	fi
else
	echo "No timing data found"
fi
