#!/bin/bash

# Identifier, do not change if modifying:
#DarkyenusTimeTrackerHookScript00003

# Script (can be modified, but may be overwritten if new plugin version is installed):

if [ "$2" = "merge" ] || [ "$2" = "squash" ]
then
	echo "Not injecting time into $2 commit"
	exit 0
fi

# Do not append time if the commit message is empty, because such commit will not happen
COMMIT_MESSAGE_LINES=$(cat "$1" | sed -e '/^#.*$/ d' -e '/^[[:space:]]*$/ d' | wc -l)
if [ "$2" = "message" ] && (($COMMIT_MESSAGE_LINES == 0))
then
	echo "Not injecting time into cancelled commit"
	exit 0
fi

# Do not append time to amend commits - those already may have the time appended.
# The only way to detect amend commit is the check whether or not the first line of commit message is empty.
# That however does not work for "message" type commits (commit -m), but that is not a big deal,
# as those won't have the time appended anyway, so they are not problematic.
FIRST_COMMIT_LINE=$(head -n 1 "$1")
if [ "$2" == "commit" ] && [ -n "$FIRST_COMMIT_LINE" ]
then
	echo "Not injecting time into amend commit"
	exit 0
fi

DTT_TIME="$(dirname "$0")/../.darkyenus_time_tracker_commit_time"

if [ -e "$DTT_TIME" ]
then
	TIME_TOTAL_SEC=$(cat ${DTT_TIME})
	TIME_REMAINING_SEC="$TIME_TOTAL_SEC"
	TIME_MESSAGE=""
	if (($TIME_TOTAL_SEC >= 3600))
	then
		TIME_MESSAGE="$TIME_MESSAGE $(($TIME_REMAINING_SEC / 3600)) hour"
		if (($TIME_REMAINING_SEC / 3600 != 1))
		then
		    TIME_MESSAGE="${TIME_MESSAGE}s"
		fi
		TIME_REMAINING_SEC=$(($TIME_REMAINING_SEC % 3600))
	fi

	if (($TIME_TOTAL_SEC >= 60))
	then
		TIME_MESSAGE="$TIME_MESSAGE $(($TIME_REMAINING_SEC / 60)) minute"
		if (($TIME_REMAINING_SEC / 60 != 1))
		then
			TIME_MESSAGE="${TIME_MESSAGE}s"
		fi
        TIME_REMAINING_SEC=$(($TIME_REMAINING_SEC % 60))
	fi

	if (($TIME_TOTAL_SEC > 0))
	then
		if (($TIME_TOTAL_SEC < 60))
		then
			TIME_MESSAGE="$TIME_MESSAGE $TIME_REMAINING_SEC second"
			if (($TIME_REMAINING_SEC != 1))
	        then
	            TIME_MESSAGE="${TIME_MESSAGE}s"
	        fi
        fi

        printf "\n\nTook$TIME_MESSAGE" >> "$1"
        echo "0" > "$DTT_TIME"
        echo "Commit took$TIME_MESSAGE"
    else
        echo "Commit took no time, not recording"
	fi
else
	echo "No timing data found"
fi
